/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GameStatus = IDL.Text;
export const PlayerRole = IDL.Text;
export const FENString = IDL.Text;
export const GameSummary = IDL.Record({
  'status' : GameStatus,
  'turn' : PlayerRole,
  'gameId' : IDL.Nat,
  'currentPosition' : FENString,
  'black' : IDL.Text,
  'white' : IDL.Text,
});
export const Player = IDL.Record({
  'id' : IDL.Principal,
  'fullName' : IDL.Text,
  'isSubscriber' : IDL.Bool,
});
export const Subscription = IDL.Text;
export const Time = IDL.Int;

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelGame' : IDL.Func([IDL.Nat], [], []),
  'createGame' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'getActiveGames' : IDL.Func([], [IDL.Vec(GameSummary)], ['query']),
  'getCallerPlayerStats' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFinishedGames' : IDL.Func([], [IDL.Vec(GameSummary)], ['query']),
  'getPlayerGameHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Nat)],
      ['query'],
    ),
  'getPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getUserSubscriptions' : IDL.Func(
      [Subscription],
      [IDL.Vec(IDL.Tuple(IDL.Principal, Time))],
      ['query'],
    ),
  'grantSubscription' : IDL.Func([IDL.Principal, Time], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinGame' : IDL.Func([IDL.Nat], [], []),
  'makeMove' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'registerPlayer' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'resignGame' : IDL.Func([IDL.Nat], [], []),
  'revokeSubscription' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GameStatus = IDL.Text;
  const PlayerRole = IDL.Text;
  const FENString = IDL.Text;
  const GameSummary = IDL.Record({
    'status' : GameStatus,
    'turn' : PlayerRole,
    'gameId' : IDL.Nat,
    'currentPosition' : FENString,
    'black' : IDL.Text,
    'white' : IDL.Text,
  });
  const Player = IDL.Record({
    'id' : IDL.Principal,
    'fullName' : IDL.Text,
    'isSubscriber' : IDL.Bool,
  });
  const Subscription = IDL.Text;
  const Time = IDL.Int;
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelGame' : IDL.Func([IDL.Nat], [], []),
    'createGame' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'getActiveGames' : IDL.Func([], [IDL.Vec(GameSummary)], ['query']),
    'getCallerPlayerStats' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFinishedGames' : IDL.Func([], [IDL.Vec(GameSummary)], ['query']),
    'getPlayerGameHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'getPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getUserSubscriptions' : IDL.Func(
        [Subscription],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Time))],
        ['query'],
      ),
    'grantSubscription' : IDL.Func([IDL.Principal, Time], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinGame' : IDL.Func([IDL.Nat], [], []),
    'makeMove' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'registerPlayer' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'resignGame' : IDL.Func([IDL.Nat], [], []),
    'revokeSubscription' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };