/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type FENString = string;
export type GameStatus = string;
export interface GameSummary {
  'status' : GameStatus,
  'turn' : PlayerRole,
  'gameId' : bigint,
  'currentPosition' : FENString,
  'black' : string,
  'white' : string,
}
export interface Player {
  'id' : Principal,
  'fullName' : string,
  'isSubscriber' : boolean,
}
export type PlayerRole = string;
export type Subscription = string;
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelGame' : ActorMethod<[bigint], undefined>,
  'createGame' : ActorMethod<[bigint, bigint], bigint>,
  'getActiveGames' : ActorMethod<[], Array<GameSummary>>,
  'getCallerPlayerStats' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFinishedGames' : ActorMethod<[], Array<GameSummary>>,
  'getPlayerGameHistory' : ActorMethod<[Principal], Array<bigint>>,
  'getPlayers' : ActorMethod<[], Array<Player>>,
  'getUserSubscriptions' : ActorMethod<
    [Subscription],
    Array<[Principal, Time]>
  >,
  'grantSubscription' : ActorMethod<[Principal, Time], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinGame' : ActorMethod<[bigint], undefined>,
  'makeMove' : ActorMethod<[bigint, bigint, bigint, bigint, bigint], undefined>,
  'registerPlayer' : ActorMethod<[string, string], undefined>,
  'resignGame' : ActorMethod<[bigint], undefined>,
  'revokeSubscription' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];